// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cowjsrngyhpofjvbwsov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvd2pzcm5neWhwb2ZqdmJ3c292Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0OTgyMjYsImV4cCI6MjA2NDA3NDIyNn0.7H20-02TQWVoT__h73Nqselxp-_Q54EvxN26iFRqyZ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);